name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.4"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Verify tests directory exists
      run: |
        if [ -d "tests" ]; then
          echo "Tests directory exists."
        else
          echo "Tests directory does not exist."
          exit 1
        fi
    - name: Verify contents of tests directory
      run: |
        ls tests
    - name: Print working directory
      run: |
        pwd
    - name: Print Python path
      run: |
        python -c "import sys; print(sys.path)"
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Running unit tests
      run: |
        python -m unittest discover -s tests -p "test_spotify_app.py"
